local char_ids = {
    Ryu = 1, 
    Luke = 2, 
    Kimberly = 3, 
    ChunLi = 4, 
    Manon = 5, 
    Zangief = 6, 
    JP = 7, 
    Dhalsim = 8, 
    Cammy = 9, 
    Ken = 10, 
    DeeJay = 11, 
    Lily = 12, 
    AKI = 13, 
    Rashid = 14, 
    Blanka = 15, 
    Juri = 16, 
    Marisa = 17, 
    Guile = 18, 
    Ed = 19,
    EHonda = 20, 
    Jamie = 21, 
    Akuma = 22, 
    MBison = 26, 
    Terry = 27,
    Mai = 28,
    Elena = 29,
    Sagat = 25,
    CViper = 30
}

return char_ids